# docker-compose.yml
services:
  # ... service postgres ...
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8080"
    environment:
      # On utilise les noms de variables définis dans application.properties
      - DB_URL=jdbc:postgresql://postgres:5432/mydatabase
      - DB_USER=user
      - DB_PASS=password
    healthcheck:
      # ... reste du healthcheck ...
